# Generated by Django 3.2.7 on 2021-10-01 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField()),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_expired', models.DateTimeField()),
                ('is_done', models.BooleanField(default=False)),
                ('date_done', models.DateTimeField(auto_now=True)),
                ('weight', models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'user_tasks',
                'ordering': ['date_expired'],
            },
        ),
    ]
