# Generated by Django 3.2.7 on 2021-10-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='date_done',
            field=models.DateTimeField(null=True),
        ),
    ]
