# Generated by Django 3.2.7 on 2021-10-02 08:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_alter_task_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['name'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='usertask',
            options={'ordering': ['date_expired'], 'verbose_name': 'Задача пользователя', 'verbose_name_plural': 'Задачи пользователя'},
        ),
        migrations.AlterField(
            model_name='task',
            name='desc',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='date_done',
            field=models.DateTimeField(null=True, verbose_name='Время сдачи'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='date_expired',
            field=models.DateTimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='id_manager',
            field=models.ForeignKey(db_column='id_manager', on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='id_task',
            field=models.ForeignKey(db_column='id_task', on_delete=django.db.models.deletion.CASCADE, to='api.task', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Выполнена?'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='weight',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Вес'),
        ),
    ]
