# Generated by Django 3.2.7 on 2021-10-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211002_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignchat',
            name='tg_link',
            field=models.URLField(max_length=300, verbose_name='Telegram'),
        ),
    ]
