# Generated by Django 3.2.7 on 2021-10-02 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userrank',
            options={'ordering': ['name'], 'verbose_name': 'Ранг пользователя', 'verbose_name_plural': 'Ранги пользователя'},
        ),
        migrations.AlterModelOptions(
            name='usertype',
            options={'ordering': ['name'], 'verbose_name': 'Тип пользователя', 'verbose_name_plural': 'Типы пользователя'},
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=150, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_user_rank',
            field=models.ForeignKey(db_column='id_user_rank', on_delete=django.db.models.deletion.CASCADE, to='authentication.userrank', verbose_name='Ранг пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_user_type',
            field=models.ForeignKey(db_column='id_user_type', on_delete=django.db.models.deletion.CASCADE, to='authentication.usertype', verbose_name='Тип пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Сотрудник?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Суперпользователь?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(null=True, verbose_name='Время последнего входа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=300, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='userrank',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
